[tool.poetry]
name = "sql"
version = "0.1.0"
description = "sql server"
authors = ["liu"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pypyodbc = "^1.3.6"
pandas = "^2.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
